import { defineScreens, type ScreenId } from "../dsl"
import { executableScreens } from "../../scenarios"
import { taxonomies } from "./taxonomies"

export const screens = defineScreens(taxonomies, {
  home: {
    title: "Home",
    category: "system",
    screenLabels: ["start-screen", "new-session", "composer"],
    uiElements: ["composer", "keyboard-hints", "full-screen-view", "empty-state"],
    surfaces: "full-screen",
    patterns: "landing",
    features: ["system", "session"],
    states: "empty",
  },
  "command-palette": {
    title: "Command palette",
    category: "navigation",
    screenLabels: ["command-navigation"],
    uiElements: ["command-palette", "search-field", "list", "keyboard-hints", "dialog"],
    surfaces: "modal",
    patterns: "palette",
    features: ["commands", "navigation"],
    states: "default",
  },
  "model-picker": {
    title: "Model picker",
    category: "picker",
    screenLabels: ["model-selection"],
    uiElements: ["picker", "search-field", "single-select", "list", "dialog", "keyboard-hints"],
    surfaces: "modal",
    patterns: "picker",
    features: "model",
    states: "default",
  },
  "agent-picker": {
    title: "Agent picker",
    category: "picker",
    screenLabels: ["agent-selection"],
    uiElements: ["picker", "search-field", "single-select", "list", "dialog", "keyboard-hints"],
    surfaces: "modal",
    patterns: "picker",
    features: "agent",
    states: "default",
  },
  "integration-picker": {
    title: "Integrations",
    category: "picker",
    screenLabels: ["integration-setup"],
    uiElements: ["picker", "single-select", "list", "dialog"],
    surfaces: "modal",
    patterns: "picker",
    features: "integration",
    states: "default",
  },
  "theme-picker": {
    title: "Theme picker",
    category: "picker",
    screenLabels: ["theme-selection"],
    uiElements: ["picker", "single-select", "list", "dialog"],
    surfaces: "modal",
    patterns: "picker",
    features: "theme",
    states: "default",
  },
  "mcp-list": {
    title: "MCPs",
    category: "status",
    screenLabels: ["mcp-management"],
    uiElements: ["list", "dialog", "empty-state"],
    surfaces: "modal",
    patterns: "list",
    features: "mcp",
    states: "empty",
  },
  status: {
    title: "Status",
    category: "status",
    screenLabels: ["system-status", "mcp-management"],
    uiElements: ["status-indicator", "list", "dialog", "empty-state"],
    surfaces: "modal",
    patterns: "status",
    features: ["system", "mcp"],
    states: "empty",
  },
  debug: {
    title: "Debug",
    category: "information",
    screenLabels: ["debugging", "system-status"],
    uiElements: ["debug-information", "dialog"],
    surfaces: "modal",
    patterns: "info",
    features: ["debug", "system"],
    states: "default",
  },
  help: {
    title: "Help",
    category: "information",
    screenLabels: ["help-reference", "command-navigation"],
    uiElements: ["shortcut-list", "keyboard-hints", "dialog", "list"],
    surfaces: "modal",
    patterns: "info",
    features: ["help", "shortcuts"],
    states: "default",
  },
  pair: {
    title: "Pair device",
    category: "information",
    screenLabels: ["device-pairing", "integration-setup"],
    uiElements: ["qr-code", "dialog"],
    surfaces: "modal",
    patterns: "pairing",
    features: "device",
    states: "default",
  },
  "session-picker": {
    title: "Session picker",
    category: "session",
    screenLabels: ["session-list"],
    uiElements: ["picker", "search-field", "single-select", "list", "dialog", "keyboard-hints", "empty-state"],
    surfaces: "modal",
    patterns: "picker",
    features: "session",
    states: "empty",
  },
  "skill-picker": {
    title: "Skill picker",
    category: "session",
    screenLabels: ["skill-selection"],
    uiElements: ["picker", "search-field", "single-select", "list", "dialog", "keyboard-hints"],
    surfaces: "modal",
    patterns: "picker",
    features: "skill",
    states: "default",
  },
  ...executableScreens,
  "session-rename": {
    title: "Rename session",
    category: "session",
    screenLabels: ["rename-session"],
    uiElements: ["dialog", "form", "text-input"],
    surfaces: "modal",
    patterns: "form",
    features: "session",
    states: "default",
  },
  "session-fork": {
    title: "Fork session",
    category: "session",
    screenLabels: ["fork-session"],
    uiElements: ["dialog", "picker", "single-select", "list"],
    surfaces: "modal",
    patterns: "picker",
    features: "session",
    states: "default",
  },
  "session-export": {
    title: "Export session",
    category: "session",
    screenLabels: ["export-session"],
    uiElements: ["dialog", "form", "single-select", "button-group"],
    surfaces: "modal",
    patterns: "form",
    features: ["session", "export"],
    states: "default",
  },
  "question-prompt": {
    title: "Question prompt",
    category: "session",
    screenLabels: ["question-response", "tool-execution"],
    uiElements: ["inline-prompt", "question-prompt", "form", "single-select", "button-group", "confirmation"],
    surfaces: "inline",
    patterns: "form",
    features: ["question", "tool"],
    states: "confirmation",
  },
  "session-picker-populated": {
    title: "Session picker (populated)",
    category: "session",
    screenLabels: ["session-list"],
    uiElements: ["picker", "search-field", "single-select", "list", "dialog", "keyboard-hints"],
    surfaces: "modal",
    patterns: "picker",
    features: "session",
    states: "populated",
  },
  "toast-success": {
    title: "Success toast",
    category: "system",
    screenLabels: ["export-session", "toast-success"],
    uiElements: ["toast", "confirmation", "transcript"],
    surfaces: "toast",
    patterns: "notification",
    features: ["session", "export", "notification"],
    states: "success",
  },
  "toast-info": {
    title: "Info toast",
    category: "system",
    screenLabels: ["debugging", "toast-info"],
    uiElements: ["toast", "confirmation"],
    surfaces: "toast",
    patterns: "notification",
    features: ["debug", "notification"],
    states: "default",
  },
  "toast-error": {
    title: "Error toast",
    category: "system",
    screenLabels: ["error-recovery", "toast-error"],
    uiElements: ["toast", "error-report"],
    surfaces: "toast",
    patterns: "notification",
    features: "notification",
    states: "error",
  },
  "diff-viewer": {
    title: "Diff viewer",
    category: "session",
    screenLabels: ["diff-review"],
    uiElements: ["full-screen-view", "list", "keyboard-hints", "empty-state"],
    surfaces: "full-screen",
    patterns: "list",
    features: ["diff", "session"],
    states: "empty",
  },
})

export type CaptureId = ScreenId<typeof screens>
